import random
import sys

animal = ["", "Aardvark:",
    "Albatross:",
    "Alligator:",
    "Alpaca:",
    "Ant:",
    "Anteater:",
    "Antelope:",
    "Ape:",
    "Armadillo:",
    "Donkey:",
    "Baboon:",
    "Badger:",
    "Barracuda:",
    "Bat:",
    "Bear:",
    "Beaver:",
    "Bee:",
    "Bison:",
    "Boar:",
    "Buffalo:",
    "Butterfly:",
    "Camel:",
    "Capybara:",
    "Caribou:",
    "Cassowary:",
    "Cat:",
    "Caterpillar:",
    "Cattle:",
    "Chamois:",
    "Cheetah:",
    "Chicken:",
    "Chimpanzee:",
    "Chinchilla:",
    "Chough:",
    "Clam:",
    "Cobra:",
    "Cockroach:",
    "Cod:",
    "Cormorant:",
    "Coyote:",
    "Crab:",
    "Crane:",
    "Crocodile:",
    "Crow:",
    "Curlew:",
    "Deer:",
    "Dinosaur:",
    "Dog:",
    "Dogfish:",
    "Dolphin:",
    "Dotterel:",
    "Dove:",
    "Dragonfly:",
    "Duck:",
    "Dugong:",
    "Dunlin:",
    "Eagle:",
    "Echidna:",
    "Eel:",
    "Eland:",
    "Elephant:",
    "Elk:",
    "Emu:",
    "Falcon:",
    "Ferret:",
    "Finch:",
    "Fish:",
    "Flamingo:",
    "Fly:"]


with open("catto.txt", "wb") as f:
    for i in range(100000):
        x = random.choice(animal)
        y = random.random()*100        
        f.write(f"{x} {y}\n".encode('utf8'))
